apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-mq1-ibm-mq-0
  labels:
    appname: mq1
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ocs-storagecluster-ceph-rbdmirror
  resources:
    requests:
      storage: 20Gi
